/**
 * Terminal shop upgrades — Subroutines, Exploits, and Kernel Optimizations
 */

export const UPGRADE_TYPE = {
  SUBROUTINE: 'subroutine',  // Permanent passive buff
  EXPLOIT: 'exploit',         // Limited-use active tool
  KERNEL: 'kernel',           // Base stat increase
}

export const UPGRADES = {
  // === SUBROUTINES (Passives) ===
  heuristics: {
    id: 'heuristics',
    name: 'HEURISTICS.exe',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Highlights cells adjacent to exactly 1 mine with a subtle indicator',
    cost: 60,
    maxLevel: 1,
    effect: 'Cells with value "1" pulse gently when revealed',
  },
  crypto_nodes: {
    id: 'crypto_nodes',
    name: 'CRYPTO_NODE.dll',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Cache gain multiplied by clear speed bonus',
    cost: 80,
    maxLevel: 3,
    effect: '+15% cache per level when completing node under par time',
  },
  packet_sniffer: {
    id: 'packet_sniffer',
    name: 'PKT_SNIFF.sys',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Displays mine counts on row/column headers',
    cost: 100,
    maxLevel: 1,
    effect: 'Row and column mine counts visible on grid edges',
  },
  entropy_harvester: {
    id: 'entropy_harvester',
    name: 'ENTROPY_HARV.bin',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Earn bonus entropy for each cell cleared in flood fills',
    cost: 70,
    maxLevel: 2,
    effect: '+1 entropy per cell in cascading reveals per level',
  },
  auto_flag: {
    id: 'auto_flag',
    name: 'AUTO_FLAG.cfg',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Automatically flags obvious mines when all neighbors are revealed',
    cost: 120,
    maxLevel: 1,
    effect: 'Mines surrounded by fully revealed cells get auto-flagged',
  },
  ledger_link: {
    id: 'ledger_link',
    name: 'LEDGER_LINK.prt',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Chains correctly flagged mines and validates blocks every 5 links',
    cost: 110,
    maxLevel: 1,
    effect: 'Neon links connect correct flags; validated blocks pulse-reveal nearby safe tiles',
  },
  hot_swap: {
    id: 'hot_swap',
    name: 'HOT_SWAP.bin',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Firewall mine-hit converts that mine to safe memory and auto-clears a nearby tile',
    cost: 130,
    maxLevel: 1,
    effect: 'Mine removed on firewall absorb; 1 random adjacent hidden safe tile is cleared for free',
  },
  zero_day: {
    id: 'zero_day',
    name: 'ZERO_DAY.patch',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'First three reveals on each node are forced zero-opening clicks',
    cost: 145,
    maxLevel: 1,
    effect: 'Guarantees strong openings on reveal #1-#3 of every node',
  },
  mining_rig: {
    id: 'mining_rig',
    name: 'MINING_RIG.service',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Passive cache drip while clearing safe tiles',
    cost: 120,
    maxLevel: 1,
    effect: '+1 cache per 10 safe tiles revealed, doubled while a 5+ ledger chain is active',
  },
  brute_force: {
    id: 'brute_force',
    name: 'BRUTE_FORCE.lib',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Danger-adaptive number rendering with high-threat pulse markers',
    cost: 90,
    maxLevel: 1,
    effect: '1-2 dim green, 3-4 amber, 5+ pulsing red',
  },
  dark_pool: {
    id: 'dark_pool',
    name: 'DARK_POOL.net',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Expands terminal offers and injects a hidden half-off deal',
    cost: 160,
    maxLevel: 1,
    effect: 'Terminal shows 4 offers per category and one is always 50% off with redacted name until hover',
  },
  deep_packet: {
    id: 'deep_packet',
    name: 'DEEP_PACKET.pass',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Hovering flagged cells shows confidence estimate',
    cost: 75,
    maxLevel: 1,
    effect: 'Displays likelihood percentage for hovered flags',
  },
  ghost_thread: {
    id: 'ghost_thread',
    name: 'GHOST_THREAD.pass',
    type: UPGRADE_TYPE.SUBROUTINE,
    description: 'Chain momentum degrades instead of hard reset on disconnect',
    cost: 60,
    maxLevel: 1,
    effect: 'Intended for future chain-multiplier tuning; reserved passive slot',
  },

  // === EXPLOITS (Active abilities) ===
  deep_scan: {
    id: 'deep_scan',
    name: 'DEEP_SCAN.0x',
    type: UPGRADE_TYPE.EXPLOIT,
    description: 'X-ray vision: peek at a 3x3 region without revealing',
    cost: 40,
    charges: 2,
    effect: 'Temporarily shows mine locations in a 3x3 area',
  },
  bit_shift: {
    id: 'bit_shift',
    name: 'BIT_SHIFT.hex',
    type: UPGRADE_TYPE.EXPLOIT,
    description: 'Safely reveal one random hidden non-mine cell',
    cost: 50,
    charges: 2,
    effect: 'Reveals a safe cell — guaranteed no mine',
  },
  defrag: {
    id: 'defrag',
    name: 'DEFRAG.opt',
    type: UPGRADE_TYPE.EXPLOIT,
    description: 'Reveals all cells with value 0 (empty) on the board',
    cost: 90,
    charges: 1,
    effect: 'Mass reveals all zero-cells and their neighbors',
  },
  overclock: {
    id: 'overclock',
    name: 'OVERCLOCK.exe',
    type: UPGRADE_TYPE.EXPLOIT,
    description: '15-second burst mode for accelerated extraction',
    cost: 95,
    charges: 1,
    effect: 'Triples entropy from reveals for 15 seconds',
  },
  system_restore: {
    id: 'system_restore',
    name: 'SYSTEM_RESTORE.sh',
    type: UPGRADE_TYPE.EXPLOIT,
    description: 'Stabilizes transient board artifacts',
    cost: 65,
    charges: 1,
    effect: 'Clears active scan overlays and corruption visuals',
  },
  fork_chain: {
    id: 'fork_chain',
    name: 'FORK_CHAIN.cmd',
    type: UPGRADE_TYPE.EXPLOIT,
    description: 'Forces ledger resolution across currently verified mine links',
    cost: 110,
    charges: 1,
    effect: 'Mass-validates all currently completable 5-mine blocks in the active chain',
  },
  signal_jammer: {
    id: 'signal_jammer',
    name: 'SIGNAL_JAMMER.vbs',
    type: UPGRADE_TYPE.EXPLOIT,
    description: 'Injects timer drift to delay trace lock-on',
    cost: 70,
    charges: 1,
    effect: 'Adds a 30s timing offset to the active node clock',
  },
  sql_inject: {
    id: 'sql_inject',
    name: 'SQL_INJECT',
    type: UPGRADE_TYPE.EXPLOIT,
    description: 'Select a row to expose all mines through packet echo',
    cost: 40,
    charges: 1,
    effect: 'Click a row cell to reveal mine locations in that row overlay',
  },
  reboot: {
    id: 'reboot',
    name: 'REBOOT.sh',
    type: UPGRADE_TYPE.EXPLOIT,
    description: 'Reshuffles hidden tiles while preserving all revealed state',
    cost: 25,
    charges: 1,
    effect: 'Re-randomizes hidden mines and numbers to break deadlocked guesses',
  },
  docker_compose: {
    id: 'docker_compose',
    name: 'DOCKER_COMPOSE',
    type: UPGRADE_TYPE.EXPLOIT,
    description: 'Containerization protocol slot (future targeting mechanic)',
    cost: 135,
    charges: 1,
    effect: 'Reserved for 4x4 mine isolation mechanic',
  },

  // === KERNEL OPTIMIZATIONS (Stats) ===
  firewall_upgrade: {
    id: 'firewall_upgrade',
    name: 'FW_UPGRADE.patch',
    type: UPGRADE_TYPE.KERNEL,
    description: 'Adds +1 to maximum firewall capacity',
    cost: 100,
    maxLevel: 3,
    effect: '+1 max firewall per purchase',
  },
  cache_boost: {
    id: 'cache_boost',
    name: 'CACHE_BOOST.mod',
    type: UPGRADE_TYPE.KERNEL,
    description: 'Increases base cache rewards by 20%',
    cost: 80,
    maxLevel: 3,
    effect: '+20% cache rewards per level',
  },
  clock_speed: {
    id: 'clock_speed',
    name: 'CLK_SPEED.oc',
    type: UPGRADE_TYPE.KERNEL,
    description: 'Grants +30s to par time for speed bonuses',
    cost: 60,
    maxLevel: 2,
    effect: '+30s par time per level',
  },
  sudo_immortality: {
    id: 'sudo_immortality',
    name: 'sudo chmod +x immortality',
    type: UPGRADE_TYPE.KERNEL,
    description: 'Last firewall slowly regenerates over time',
    cost: 240,
    maxLevel: 1,
    requiresRoot: true,
    effect: 'Reserved kernel hook for auto-recharge firewall behavior',
  },
  sudo_uncorrupt: {
    id: 'sudo_uncorrupt',
    name: 'sudo rm -rf /corruption',
    type: UPGRADE_TYPE.KERNEL,
    description: 'Purges negative node modifiers for the run',
    cost: 260,
    maxLevel: 1,
    requiresRoot: true,
    effect: 'Reserved kernel hook for permanent modifier suppression',
  },
  sudo_symlink_win: {
    id: 'sudo_symlink_win',
    name: 'sudo ln -s /win /current_node',
    type: UPGRADE_TYPE.KERNEL,
    description: 'Bypass current node for logic bonus routing',
    cost: 300,
    maxLevel: 1,
    requiresRoot: true,
    effect: 'Reserved kernel hook for instant-node resolution',
  },
}

// Small terminal-art icons for each upgrade (5 lines tall, monospace)
export const UPGRADE_ART = {
  heuristics: [
    '┌───┐',
    '│ ? │',
    '│►1◄│',
    '│ ? │',
    '└───┘',
  ],
  crypto_nodes: [
    ' ╔═╗ ',
    '╔╝$╚╗',
    '║ ₿ ║',
    '╚╗$╔╝',
    ' ╚═╝ ',
  ],
  packet_sniffer: [
    '┌┬┬┬┐',
    '├3 2┤',
    '├ ▓ ┤',
    '├1 4┤',
    '└┴┴┴┘',
  ],
  entropy_harvester: [
    '~~~~~',
    '}{}{}',
    '│ENT│',
    '}{}{}',
    '~~~~~',
  ],
  auto_flag: [
    '  ▲  ',
    ' ▲▲▲ ',
    ' │█│ ',
    '┌┤▓├┐',
    '└───┘',
  ],
  ledger_link: [
    'o---o',
    '|\\ /|',
    '|[#]|',
    '|/ \\|',
    'o---o',
  ],
  hot_swap: [
    '╔═══╗',
    '║X↔X║',
    '║ ▓ ║',
    '║↔X↔║',
    '╚═══╝',
  ],
  zero_day: [
    '00000',
    '0---0',
    '0DAY0',
    '0---0',
    '00000',
  ],
  mining_rig: [
    '⛏⛏⛏',
    '$▓▓$',
    '$RIG$',
    '$▓▓$',
    '⛏⛏⛏',
  ],
  brute_force: [
    '1 2 3',
    '4 5 6',
    '7 8 9',
    'X X X',
    'FORCE',
  ],
  dark_pool: [
    '█████',
    '█ ? █',
    '█1/2█',
    '█ ? █',
    '█████',
  ],
  deep_packet: [
    '╭~~~╮',
    '│%?%│',
    '│⚑⚑│',
    '│%?%│',
    '╰~~~╯',
  ],
  ghost_thread: [
    ' .-. ',
    '/| |\\',
    ' |*| ',
    '\\| |/',
    " '-' ",
  ],
  deep_scan: [
    '╭───╮',
    '│ ◉ │',
    '│/█\\│',
    '│\\▓/│',
    '╰───╯',
  ],
  bit_shift: [
    '01010',
    '10>>1',
    '01001',
    '1<<10',
    '01010',
  ],
  defrag: [
    '▓▒░▓▒',
    '░▒▓░▓',
    '█▓▒░█',
    '░░░░░',
    '█████',
  ],
  overclock: [
    '╔CPU╗',
    '║+++║',
    '║15s║',
    '║+++║',
    '╚═══╝',
  ],
  system_restore: [
    '┌rst┐',
    '│↺↺│',
    '│SYS│',
    '│↺↺│',
    '└───┘',
  ],
  fork_chain: [
    'o---o',
    ' \\ / ',
    '  X  ',
    ' / \\ ',
    'o---o',
  ],
  signal_jammer: [
    '╭jam╮',
    '│###│',
    '│|||│',
    '│###│',
    '╰───╯',
  ],
  sql_inject: [
    'SELECT',
    '* FROM',
    'MINES',
    'WHERE',
    'row=?',
  ],
  reboot: [
    '┌re┐',
    '│↻│',
    '│OS│',
    '│↻│',
    '└──┘',
  ],
  docker_compose: [
    '┌4x4┐',
    '│[]│',
    '│##│',
    '│[]│',
    '└───┘',
  ],
  firewall_upgrade: [
    '┃┃┃┃┃',
    '┃█┃█┃',
    '┃┃+┃┃',
    '┃█┃█┃',
    '┃┃┃┃┃',
  ],
  cache_boost: [
    '╔$$$╗',
    '║ ▲ ║',
    '║▲▲▲║',
    '║ ▲ ║',
    '╚$$$╝',
  ],
  clock_speed: [
    '╭───╮',
    '│ ╱ │',
    '│╱  │',
    '│+30│',
    '╰───╯',
  ],
  sudo_immortality: [
    'sudo ',
    'chmod',
    '+x fw',
    'regen',
    'root!',
  ],
  sudo_uncorrupt: [
    'sudo',
    'rm -rf',
    '/corr',
    'clean',
    'root!',
  ],
  sudo_symlink_win: [
    'sudo',
    'ln -s',
    '/win',
    '/node',
    'root!',
  ],
}

export function getShopItems() {
  return Object.values(UPGRADES)
}

export function getUpgrade(id) {
  return UPGRADES[id]
}
